i am having a problem with the following     code that will throw    an exception when the...
